# Site settings
title: Computer Security
baseurl: "http://kmicinski.com/cybersecurity-course"
url: ""
description: "Computer Security: Attacks and Defenses (CMSC311 at Haverford College)."
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
