# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Computer Security"
description: here is some text
#baseurl: "https://cs.umd.edu/~micinski"
#url: "https://cs.umd.edu/~micinski" # the base hostname & protocol for your site
permalink: pretty

# Build settings
#markdown: redcarpet

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
